import networkx as nx
import matplotlib.pyplot as plt

# Create a graph
G = nx.DiGraph()

# Add nodes
G.add_nodes_from(['999',
                  '111',
                  'GP',
                  'Own accord'
                  'Ambulance',
                  'Reception',
                  'Safe Space',
                  'A Majors',
                  'P Majors',
                  'Resus',
                  'Isolation',
                  'MH Room',
                  'Safe Space',
                  'Urgent WR',
                  'ASU',
                  'AFU',
                  'AMU',
                  'ED A WR',
                  'ED P WR',
                  'Initial Streaming',
                  'RAT/Triage',
                  'Initial CA',
                  'Surge',
                  'PAU',
                  'ICU',
                  'M Ward',
                  'S Ward',
                  'OHD',
                  'Theatres',
                  'D - CT',
                  'D - X-Ray',
                  'D - MRI',
                  'D - Bloods',
                  'D Lounge',
                  'UTC',
                  'SDEC',
                  'CDU',
                  'MH Department',
                  'Exit Hospital'
                  ])

# Add edges with attributes
edges_with_acuity = [('999', 'Ambulance', '1-2'),
                     ('999', 'Ambulance', '3'),
                     ('999', 'Ambulance', '4-5'),
                     ('111', 'Ambulance', '1-2'),
                     ('111', 'Ambulance', '3'),
                     ('111', 'Walk-in', '3'),
                     ('111', 'Direct referral', '3'),
                     ('111', 'Walk-in', '4-5'),
                     ('111', 'Direct referral', '4-5'),
                     ('GP', 'Ambulance', '1-2'),
                     ('GP', 'Ambulance', '3'),
                     ('GP', 'Walk-in', '3'),
                     ('GP', 'Direct referral', '3'),
                     ('GP', 'Walk-in', '4-5'),
                     ('GP', 'Direct referral', '4-5'),
                     ('Own accord', 'Walk-in', '1-2'),
                     ('Own accord', 'Walk-in', '3'),
                     ('Own accord', 'Walk-in', '4-5'),
                     ('Ambulance', 'MH Room', '1-2'),
                     ('Ambulance', 'Resus', '1-2'),
                     ('Ambulance', 'Isolation', '1-2'),
                     ('Ambulance', 'Triaging', '3'),
                     ('Ambulance', 'MH Room', '3'),
                     ('Ambulance', 'Majors', '3'),
                     ('Ambulance', 'Safe Space', '3'),
                     ('Ambulance', 'UTC', '3'),
                     ('Ambulance', 'SDEC', '3'),
                     ('Ambulance', 'Triaging', '4-5'),
                     ('Ambulance', 'MH Room', '4-5'),
                     ('Ambulance', 'UTC', '4-5'),
                     ('Ambulance', 'SDEC', '4-5'),
                     ('Walk-in', 'Reception', '1-2'),
                     ('Walk-in', 'Reception', '3'),
                     ('Walk-in', 'Urgent WR', '3'),
                     ('Walk-in', 'Reception', '4-5'),
                     ('Walk-in', 'Urgent WR', '4-5'),
                     ('Direct referral', 'Urgent WR', '3'),
                     ('Direct referral', 'Urgent WR', '4-5'),
                     ('Reception', 'Streaming', '1-2'),
                     ('Reception', 'Isolation', '1-2'),
                     ('Reception', 'Streaming', '3'),
                     ('Reception', 'Streaming', '4-5'),
                     ('Streaming', 'Triaging', '1-2'),
                     ('Streaming', 'Triaging', '3'),
                     ('Streaming', 'Triaging', '4-5'),
                     ('Triaging', 'ED A WR', '1-2'),
                     ('Triaging', 'ED P WR', '1-2'),
                     ('Triaging', 'ED A WR', '3'),
                     ('Triaging', 'ED P WR', '3'),
                     ('Triaging', 'Urgent WR', '3'),
                     ('Triaging', 'ED A WR', '4-5'),
                     ('Triaging', 'ED P WR', '4-5'),
                     ('Triaging', 'Urgent WR', '4-5'),
                     ('ED P WR', 'Resus', '1-2'),
                     ('ED P WR', 'Surge', '1-2'),
                     ('ED P WR', 'P Majors', '3'),
                     ('ED P WR', 'Surge', '3'),
                     ('ED P WR', 'PAU', '4-5'),
                     ('ED P WR', 'Surge', '4-5'),
                     ('ED A WR', 'Resus', '1-2'),
                     ('ED A WR', 'MH Room', '1-2'),
                     ('ED A WR', 'Surge', '1-2'),
                     ('ED A WR', 'A Majors', '3'),
                     ('ED A WR', 'MH Room', '3'),
                     ('ED A WR', 'Surge', '3'),
                    ('Resus', 'ICU', '1-2'),
                    ('Resus', 'Theatres', '1-2'),
                    ('Resus', 'D - CT', '1-2'),
                    ('Resus', 'D - MRI', '1-2'),
                    ('P Majors', 'Theatres', '3'),
                    ('P Majors', 'M Ward', '3'),
                    ('P Majors', 'S Ward', '3'),
                    ('P Majors', 'OHD', '3'),
                    ('P Majors', 'D - CT', '3'),
                    ('P Majors', 'D - MRI', '3'),
                    ('P Majors', 'MH Department', '3'),
                    ('A Majors', 'Theatres', '3'),
                    ('A Majors', 'M Ward', '3'),
                    ('A Majors', 'S Ward', '3'),
                    ('A Majors', 'OHD', '3'),
                    ('A Majors', 'D - CT', '3'),
                    ('A Majors', 'D - MRI', '3'),
                    ('A Majors', 'MH Department', '3'),
                    ('Isolation', 'ICU', '1-2'),
                    ('Isolation', 'M Ward', '1-2'),
                    ('Isolation', 'D Lounge', '1-2'),
                    ('MH Room', 'MH Department', '1-2'),
                    ('MH Room', 'D Lounge', '1-2'),
                    ('MH Room', 'MH Department', '3'),
                    ('MH Room', 'D Lounge', '3'),
                    ('MH Room', 'MH Department', '4-5'),
                    ('MH Room', 'D Lounge', '4-5'),
                    ('PAU', 'D - CT', '4-5'),
                    ('PAU', 'D - X-Ray', '4-5'),
                    ('PAU', 'D - MRI', '4-5'),
                    ('PAU', 'D - Bloods', '4-5'),
                    ('PAU', 'D Lounge', '4-5'),
                    ('Urgent WR', 'AMU', '3'),
                    ('Urgent WR', 'AFU', '3'),
                    ('Urgent WR', 'ASU', '3'),
                    ('Urgent WR', 'UTC', '3'),
                    ('Urgent WR', 'SDEC', '3'),
                    ('Urgent WR', 'CDU', '3'),
                    ('Urgent WR', 'Surge', '3'),
                    ('Urgent WR', 'AMU', '4-5'),
                    ('Urgent WR', 'AFU', '4-5'),
                    ('Urgent WR', 'ASU', '4-5'),
                    ('Urgent WR', 'UTC', '4-5'),
                    ('Urgent WR', 'SDEC', '4-5'),
                    ('Urgent WR', 'CDU', '4-5'),
                    ('Urgent WR', 'Surge', '4-5'),
                    ('AMU', 'D - CT', '3'),
                    ('AMU', 'D - X-Ray', '3'),
                    ('AMU', 'D - MRI', '3'),
                    ('AMU', 'D - Bloods', '3'),
                    ('AMU', 'OHD', '3'),
                    ('AMU', 'D Lounge', '3'),
                    ('AMU', 'D - CT', '4-5'),
                    ('AMU', 'D - X-Ray', '4-5'),
                    ('AMU', 'D - MRI', '4-5'),
                    ('AMU', 'D - Bloods', '4-5'),
                    ('AMU', 'OHD', '4-5'),
                    ('AMU', 'D Lounge', '4-5'),
                    ('AFU', 'D - CT', '3'),
                    ('AFU', 'D - X-Ray', '3'),
                    ('AFU', 'D - MRI', '3'),
                    ('AFU', 'D - Bloods', '3'),
                    ('AFU', 'OHD', '3'),
                    ('AFU', 'D Lounge', '3'),
                    ('AFU', 'D - CT', '4-5'),
                    ('AFU', 'D - X-Ray', '4-5'),
                    ('AFU', 'D - MRI', '4-5'),
                    ('AFU', 'D - Bloods', '4-5'),
                    ('AFU', 'OHD', '4-5'),
                    ('AFU', 'D Lounge', '4-5'),
                    ('ASU', 'D - CT', '3'),
                    ('ASU', 'D - X-Ray', '3'),
                    ('ASU', 'D - MRI', '3'),
                    ('ASU', 'D - Bloods', '3'),
                    ('ASU', 'OHD', '3'),
                    ('ASU', 'S Ward', '3'),
                    ('ASU', 'D Lounge', '3'),
                    ('ASU', 'D - CT', '4-5'),
                    ('ASU', 'D - X-Ray', '4-5'),
                    ('ASU', 'D - MRI', '4-5'),
                    ('ASU', 'D - Bloods', '4-5'),
                    ('ASU', 'OHD', '4-5'),
                    ('ASU', 'S Ward', '4-5'),
                    ('ASU', 'D Lounge', '4-5'),
                    ('UTC', 'D - CT', '3'),
                    ('UTC', 'D - X-Ray', '3'),
                    ('UTC', 'D - MRI', '3'),
                    ('UTC', 'D - Bloods', '3'),
                    ('UTC', 'D Lounge', '3'),
                    ('UTC', 'D - CT', '4-5'),
                    ('UTC', 'D - X-Ray', '4-5'),
                    ('UTC', 'D - MRI', '4-5'),
                    ('UTC', 'D - Bloods', '4-5'),
                    ('UTC', 'D Lounge', '4-5'),
                    ('SDEC', 'D - CT', '3'),
                    ('SDEC', 'D - MRI', '3'),
                    ('SDEC', 'M Ward', '3'),
                    ('SDEC', 'S Ward', '3'),
                    ('SDEC', 'Theatres', '3'),
                    ('SDEC', 'OHD', '3'),
                    ('SDEC', 'D Lounge', '3'),
                    ('SDEC', 'D - CT', '4-5'),
                    ('SDEC', 'D - X-Ray', '4-5'),
                    ('SDEC', 'D - MRI', '4-5'),
                    ('SDEC', 'D - Bloods', '4-5'),
                    ('SDEC', 'D Lounge', '4-5'),
                    ('CDU', 'D - CT', '3'),
                    ('CDU', 'D - MRI', '3'),
                    ('CDU', 'M Ward', '3'),
                    ('CDU', 'S Ward', '3'),
                    ('CDU', 'OHD', '3'),
                    ('CDU', 'D Lounge', '3'),
                    ('CDU', 'D - CT', '4-5'),
                    ('CDU', 'D - X-Ray', '4-5'),
                    ('CDU', 'D - MRI', '4-5'),
                    ('CDU', 'D - Bloods', '4-5'),
                    ('CDU', 'D Lounge', '4-5'),
                    ('D - CT', 'Resus', '1-2'),
                    ('D - CT', 'Surge', '1-2'),
                    ('D - CT', 'D - MRI', '1-2'),
                    ('D - CT', 'A Majors', '3'),
                    ('D - CT', 'P Majors', '3'),
                    ('D - CT', 'Surge', '3'),
                    ('D - CT', 'AMU', '3'),
                    ('D - CT', 'AFU', '3'),
                    ('D - CT', 'ASU', '3'),
                    ('D - CT', 'UTC', '3'),
                    ('D - CT', 'SDEC', '3'),
                    ('D - CT', 'CDU', '3'),
                    ('D - CT', 'D - MRI', '3'),
                    ('D - CT', 'PAU', '4-5'),
                    ('D - CT', 'Surge', '4-5'),
                    ('D - CT', 'AMU', '4-5'),
                    ('D - CT', 'AFU', '4-5'),
                    ('D - CT', 'ASU', '4-5'),
                    ('D - CT', 'UTC', '4-5'),
                    ('D - CT', 'SDEC', '4-5'),
                    ('D - CT', 'CDU', '4-5'),
                    ('D - CT', 'D - X-Ray', '4-5'),
                    ('D - CT', 'D - MRI', '4-5'),
                    ('D - CT', 'D - Bloods', '4-5'),
                    ('D - Bloods', 'D - X-Ray', '1-2'),
                    ('D - Bloods', 'AMU', '3'),
                    ('D - Bloods', 'AFU', '3'),
                    ('D - Bloods', 'ASU', '3'),
                    ('D - Bloods', 'UTC', '3'),
                    ('D - Bloods', 'SDEC', '3'),
                    ('D - Bloods', 'CDU', '3'),
                    ('D - Bloods', 'D - X-Ray', '3'),
                    ('D - Bloods', 'Minors', '4-5'),
                    ('D - Bloods', 'Surge', '4-5'),
                    ('D - Bloods', 'PAU', '4-5'),
                    ('D - Bloods', 'AMU', '4-5'),
                    ('D - Bloods', 'AFU', '4-5'),
                    ('D - Bloods', 'ASU', '4-5'),
                    ('D - Bloods', 'UTC', '4-5'),
                    ('D - Bloods', 'SDEC', '4-5'),
                    ('D - Bloods', 'CDU', '4-5'),
                    ('D - Bloods', 'D - X-Ray', '4-5'),
                    ('D - Bloods', 'D - MRI', '4-5'),
                    ('D - Bloods', 'D - CT', '4-5'),
                    ('D - X-Ray', 'D - Bloods', '1-2'),
                    ('D - X-Ray', 'AMU', '3'),
                    ('D - X-Ray', 'AFU', '3'),
                    ('D - X-Ray', 'ASU', '3'),
                    ('D - X-Ray', 'UTC', '3'),
                    ('D - X-Ray', 'SDEC', '3'),
                    ('D - X-Ray', 'CDU', '3'),
                    ('D - X-Ray', 'D - Bloods', '3'),
                    ('D - X-Ray', 'PAU', '4-5'),
                    ('D - X-Ray', 'Surge', '4-5'),
                    ('D - X-Ray', 'AMU', '4-5'),
                    ('D - X-Ray', 'AFU', '4-5'),
                    ('D - X-Ray', 'ASU', '4-5'),
                    ('D - X-Ray', 'UTC', '4-5'),
                    ('D - X-Ray', 'SDEC', '4-5'),
                    ('D - X-Ray', 'CDU', '4-5'),
                    ('D - X-Ray', 'D - Bloods', '4-5'),
                    ('D - X-Ray', 'D - MRI', '4-5'),
                    ('D - X-Ray', 'D - CT', '4-5'),
                    ('D - MRI', 'Resus', '1-2'),
                    ('D - MRI', 'Surge', '1-2'),
                    ('D - MRI', 'D - CT', '1-2'),
                    ('D - MRI', 'A Majors', '3'),
                    ('D - MRI', 'P Majors', '3'),
                    ('D - MRI', 'Surge', '3'),
                    ('D - MRI', 'AMU', '3'),
                    ('D - MRI', 'AFU', '3'),
                    ('D - MRI', 'ASU', '3'),
                    ('D - MRI', 'UTC', '3'),
                    ('D - MRI', 'SDEC', '3'),
                    ('D - MRI', 'CDU', '3'),
                    ('D - MRI', 'D - CT', '3'),
                    ('D - MRI', 'PAU', '4-5'),
                    ('D - MRI', 'Surge', '4-5'),
                    ('D - MRI', 'AMU', '4-5'),
                    ('D - MRI', 'AFU', '4-5'),
                    ('D - MRI', 'ASU', '4-5'),
                    ('D - MRI', 'UTC', '4-5'),
                    ('D - MRI', 'SDEC', '4-5'),
                    ('D - MRI', 'CDU', '4-5'),
                    ('D - MRI', 'D - Bloods', '4-5'),
                    ('D - MRI', 'D - X-Ray', '4-5'),
                    ('D - MRI', 'D - CT', '4-5'),
                    ('Surge', 'D - CT', '1-2'),
                    ('Surge', 'D - MRI', '1-2'),
                    ('Surge', 'Theatres', '1-2'),
                    ('Surge', 'M Ward', '1-2'),
                    ('Surge', 'S Ward', '1-2'),
                    ('Surge', 'OHD', '1-2'),
                    ('Surge', 'D Lounge', '1-2'),
                    ('Surge', 'D - CT', '3'),
                    ('Surge', 'D - MRI', '3'),
                    ('Surge', 'Theatres', '3'),
                    ('Surge', 'M Ward', '3'),
                    ('Surge', 'S Ward', '3'),
                    ('Surge', 'OHD', '3'),
                    ('Surge', 'D Lounge', '3'),
                    ('Surge', 'D - CT', '4-5'),
                    ('Surge', 'D - MRI', '4-5'),
                    ('Surge', 'D - Bloods', '4-5'),
                    ('Surge', 'D - X-Ray', '4-5'),
                    ('Surge', 'M Ward', '4-5'),
                    ('Surge', 'S Ward', '4-5'),
                    ('Surge', 'OHD', '4-5'),
                    ('Surge', 'D Lounge', '4-5'),
                    ('ICU', 'M Ward', '1-2'),
                    ('ICU', 'S Ward', '1-2'),
                    ('ICU', 'OHD', '1-2'),
                    ('ICU', 'Theatres', '1-2'),
                    ('MH Department', 'D Lounge', '1-2'),
                    ('MH Department', 'D Lounge', '3'),
                    ('MH Department', 'D Lounge', '4-5'),
                    ('Theatres', 'S Ward', '1-2'),
                    ('Theatres', 'S Ward', '3'),
                    ('S Ward', 'OHD', '1-2'),
                    ('S Ward', 'D Lounge', '1-2'),
                    ('S Ward', 'OHD', '3'),
                    ('S Ward', 'D Lounge', '3'),
                    ('S Ward', 'OHD', '4-5'),
                    ('S Ward', 'D Lounge', '4-5'),
                    ('M Ward', 'OHD', '1-2'),
                    ('M Ward', 'D Lounge', '1-2'),
                    ('M Ward', 'OHD', '3'),
                    ('M Ward', 'D Lounge', '3'),
                    ('M Ward', 'OHD', '4-5'),
                    ('M Ward', 'D Lounge', '4-5'),
                    ('OHD', 'D Lounge', '1-2'),
                    ('OHD', 'D Lounge', '3'),
                    ('OHD', 'D Lounge', '4-5'),
                    ('D Lounge', 'Exit Hospital', '1-2'),
                    ('D Lounge', 'Exit Hospital', '3'),
                    ('D Lounge', 'Exit Hospital', '4-5') 

                     ]

# Filter edges based on acuity
#edges_with_acuity_filtered = [(source, target, acuity) for source, target, acuity in edges_with_acuity if acuity == '1-2']
edges_with_acuity_filtered = [(source, target, acuity) for source, target, acuity in edges_with_acuity]

# Merge edges with the same source and target nodes
merged_edges = {}
for source, target, acuity in edges_with_acuity_filtered:
    if (source, target) in merged_edges:
        merged_edges[(source, target)].append(acuity)
    else:
        merged_edges[(source, target)] = [acuity]

# Add merged edges to the graph with acuity information preserved
for (source, target), acuities in merged_edges.items():
    G.add_edge(source, target, acuities=acuities)

# Draw the graph
pos = nx.shell_layout(G)  # positions for all nodes
nx.draw(G, pos, with_labels=True, node_color='skyblue', node_size=2000, font_size=12, font_weight='bold', arrows=True)

# Label edges with different colors based on acuity
edge_labels = {(u, v): ", ".join(attr['acuities']) for u, v, attr in G.edges(data=True)}
edge_colors = []
for edge in G.edges():
    u, v = edge
    acuities = edge_labels.get((u, v), '').split(', ')
    # Choose a color based on the highest acuity level among merged edges
    max_acuity = max(acuities)
    if max_acuity == '1-2':
        edge_colors.append('red')
    elif max_acuity == '3':
        edge_colors.append('green')
    elif max_acuity == '4-5':
        edge_colors.append('blue')

nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_color='black')
nx.draw_networkx_edges(G, pos, edge_color=edge_colors)

# Show the plot
plt.show()